import type { DirectorySnapshot, WorkspaceId } from './types'

/**
 * Anonymous usage, if — and only if — someone turns it on.
 *
 * The rule this file exists to enforce: nothing identifying a directory, a person, a group or a
 * machine may ever be in a payload. Counts are rounded into buckets so that even a size cannot
 * fingerprint an organisation. Building the payload is pure so it can be tested, and so the
 * "show me exactly what you send" button in Settings shows the real thing rather than a mock-up.
 */

export interface TelemetryPayload {
  /** Random per installation, regenerated by deleting the settings file. Not a machine id. */
  install: string
  version: string
  os: string
  arch: string
  /** Which workspaces have been opened this run. Names only. */
  workspacesUsed: WorkspaceId[]
  /** How many directories are open, not which. */
  domainCount: number
  objectsBucket: string
  findingsBucket: string
  reportsGenerated: number
  sessionMinutesBucket: string
}

/** Sizes are reported as ranges: an exact object count is close to an organisation's fingerprint. */
export function bucket(n: number): string {
  if (n <= 0) return '0'
  if (n < 100) return '1-99'
  if (n < 1_000) return '100-999'
  if (n < 10_000) return '1k-10k'
  if (n < 100_000) return '10k-100k'
  return '100k+'
}

export function minutesBucket(minutes: number): string {
  if (minutes < 5) return '0-5'
  if (minutes < 30) return '5-30'
  if (minutes < 120) return '30-120'
  return '120+'
}

export interface UsageFacts {
  install: string
  version: string
  os: string
  arch: string
  workspacesUsed: WorkspaceId[]
  snapshot: Pick<DirectorySnapshot, 'stats'> | null
  domainCount: number
  reportsGenerated: number
  sessionMinutes: number
}

export function buildPayload(facts: UsageFacts): TelemetryPayload {
  const objects = facts.snapshot
    ? facts.snapshot.stats.users + facts.snapshot.stats.groups + facts.snapshot.stats.computers + facts.snapshot.stats.ous
    : 0
  return {
    install: facts.install,
    version: facts.version,
    os: facts.os,
    arch: facts.arch,
    workspacesUsed: [...new Set(facts.workspacesUsed)].sort(),
    domainCount: facts.domainCount,
    objectsBucket: bucket(objects),
    findingsBucket: bucket(facts.snapshot?.stats.findings ?? 0),
    reportsGenerated: facts.reportsGenerated,
    sessionMinutesBucket: minutesBucket(facts.sessionMinutes)
  }
}

/** The only keys that may ever be sent. The server rejects anything else, and so does this. */
export const ALLOWED_KEYS: (keyof TelemetryPayload)[] = [
  'install',
  'version',
  'os',
  'arch',
  'workspacesUsed',
  'domainCount',
  'objectsBucket',
  'findingsBucket',
  'reportsGenerated',
  'sessionMinutesBucket'
]

/** Strips anything not on the list — a last line of defence against a future careless edit. */
export function sanitize(payload: TelemetryPayload): TelemetryPayload {
  const out = {} as Record<string, unknown>
  for (const key of ALLOWED_KEYS) out[key] = payload[key]
  return out as unknown as TelemetryPayload
}
